---
title: "02_Descriptive_Analysis"
author: "Vithersan Somasundaram"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Importing cleand data, include=FALSE}
# Importing Cleaned Data
  # Contains Switzerland and Zimbabwe:
dd <- readRDS(file = "../data/COVID19.rds")

# Loading Librarires:
library(tidyverse)
library(ggpubr)

unique(dd$latitude)
unique(dd$longitude)

```

Calculating new variables for the Analysis:

* We need month variables:
```{r CreateNewVariable, include=FALSE}

# Summary daily deaths for both Country:
by(dd$deaths,dd$administrative_area_level_1, summary)

```




```{r daily_death, echo=FALSE}
# Plot daily Deaths ####
ggplot(data = dd, aes(x = date, y = dailydeaths, col=administrative_area_level_1, fill=administrative_area_level_1)) +
  geom_point(alpha= 1, size= 0.5) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_line()+
  labs(x= "Date", y= "Daily New Deaths") +
  theme_linedraw()
  
ggplot(dd, aes(date, per100, col=administrative_area_level_1, fill=administrative_area_level_1)) +
  geom_point(alpha= 1, size= 0.5) +  
  labs(x= "Date", y= "Daily New Deaths per 100k People") + 
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_linedraw()

ggplot(dd, aes(date, per100, col=administrative_area_level_1, fill=administrative_area_level_1)) +
  geom_point(alpha= 0.5, size= 0.5) +  
  labs(x= "Date", y= "Daily New Deaths per 100k People") + 
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_linedraw()
```


```{r}
#maybe visualization somehow with this
require(maps)
library(fields)
dd$longitude[1]
n<-5
longitude<-seq(from = -30,to=30, length.out =n)
latitude <-seq(from = 30,to=70, length.out =n)
grid <- as.matrix(expand.grid("longitude"=c(longitude),"latitude"=c(latitude)))
z_value <-matrix(apply(grid, 1, function(x) x=x), n, n)

image.plot(x=longitude, y=latitude, z=z_value,xlab = "Longitude", ylab ="Latitude",main = "Relative")
map("world", add=T,main="World")

```



